### ISSUE TITLE
Dataset Download Issue

### ISSUE THREAD

**Issue by GunesYurdakul** [cartopy/ConvMF#5]
While trying to download dataset I am getting 403 Forbidden Error "You don't have permission to access /~cartopy/ConvMF/data/ on this server." 
It was working last week, can you please fix it?

**Comment by jchliu** [comment]
I also have this problem. Can you got the datasets?

**Comment by kongshuchen** [comment]
Me too, and i can not concat the author. I want to have these dataset for research.^_^

**Comment by jchliu** [comment]
If you send email to the author?

**Comment by kongshuchen** [comment]
Yes， i send email to him and ask for the dataset on his facebook. but he dosen't give me a reply.

**Comment by jchliu** [comment]
你是今天给作者发的邮件吗

**Comment by kongshuchen** [comment]
我前几天发的，待会我再看一下，现在在外面

**Comment by cartopy** [comment]
I solved the issue. Please check it.
